### ISSUE TITLE
No onModelChange event emitted when the component is initialized with empty/non-empty ngModel

### ISSUE THREAD

**Issue by premsair** [softsimon/ngx-bootrap-multiselect#126]
When we create the component with the options to be selected in the drop down by setting ngModel, no event is emitted for ngModelChange. However when we select/unselect the options, ngModelChange event is fired.

**Comment by chris--jones** [comment]
This semantically sounds more like an initialisation event rather than a model "change" - why do you need to know when the component is initialised?

**Comment by premsair** [comment]
When i create the component with empty/non-empty options, i want to be able to get notified of the component creation with selectedOptions (either empty or non-empty) so that i can use them to update another view that shows the selectedOptions in descriptive way. The event is emitted whenever selectedOptions are updated( from setSelected method) after the initialization but not the first time because setSelected is not being called then. Right now I am using ngOnChanges/ngDoCheck hook in my component to do that.
