### ISSUE TITLE
Add the ability to setup default options for the whole application.

### ISSUE THREAD

**Issue by dietergeerts** [softsimon/ngx-bootrap-multiselect#135]
We now have to set the same options on each multiple select, as we don't use the hard-coded ones. Can the ability to set the default options be added, or if it's already there, please tell me how I can do this.

**Comment by dietergeerts** [comment]
That's what I've done now, but when I see the settings option in the html, I always thing: 'that are custom settings'. Default settings is something that you set once, and then they count for the whole application, unless you set custom ones. It makes is easier to work with, and more semantic/readable.

**Comment by nicholasguyett** [comment]
It might be good to add a global config hook (via providers, most likely) to make application-level defaults.  If nobody else implements this by the weekend, I'll try to take a swing at it.

**Comment by SerdarN92** [comment]
You have a solution @nicholasguyett ?
