### ISSUE TITLE
Ability to append to Body 

### ISSUE THREAD

**Issue by touqeershafi** [softsimon/ngx-bootrap-multiselect#163]
- [ ]  Feature Request

## Current Behavior
When click on the select button to open dropdown, it opens in parent container, which can do problems when you are using it in popups or modals because those have `overflow:hidden` property enabled.

## Expected Behavior
It should have ability to append it on body, which will solve `overflow:hidden` problem in parents container, you can also see [ngx-bootstrap dropdown](http://valor-software.com/ngx-bootstrap/#/dropdowns#container-body) for the reference.

**Comment by touqeershafi** [comment]
@chris--jones do we have any milestone for this ?

**Comment by maxkorz** [comment]
Any news on this?

**Comment by natcohen** [comment]
@softsimon Any chance this "feature" will be added soon?

**Comment by softsimon** [comment]
@natcohen I wouldn't know because I am not maintaining this lib by adding new features currently. I'll merge a PR if someone make it.
