### ISSUE TITLE
Display dropdown content on top if there's not enough space on bottom of dropdown

### ISSUE THREAD

**Issue by siddharthaReddy** [softsimon/ngx-bootrap-multiselect#165]
Is it possible to display dropdown content on top if there's not enough space on bottom. I have a very long form where the multiselect dropdown almost falls to bottom of the page. When the dropdown button is clicked, the page extends and gets a scrollbar to display content options. 

Not sure if this was requested before. So opening a new enhancement ticket. 

P.S: I am still on version 0.3.2. Can't update to latest as the angular version we are using is still 2.x.

**Comment by chris--jones** [comment]
You can add `dropup` to containerClasses in configuration to achieve this.

Try it out on my demo page: https://chris--jones.github.io/angular-2-dropdown-multiselect/

**Comment by DaniShalash** [comment]
Unfortunately it doesn't work with the latest bootstrap 4 beta, any idea how to work around it?
