### ISSUE TITLE
When user select an option, put on video the ID instead of NAME

### ISSUE THREAD

**Issue by DarioN1** [softsimon/ngx-bootrap-multiselect#170]
Is is possible to put on video the corresponding ID istead of the NAME ?

And also, is is possible to customize it using a user pattern?

Thanks

**Comment by chris--jones** [comment]
You're trying to return the selected id from the control to play a video?
It should be as simple as binding to the onChange event
```typescript    
onChange() {
  playVideo(this.optionsModel[0]);
}
```
```typescript
<ss-multiselect-dropdown (ngModelChange)="onChange($event)" [(ngModel)]="optionsModel"> ...</ss-multiselect-dropdown>
```
