### ISSUE TITLE
Add an option NOT to add parent id to the model when all of its children are selected

### ISSUE THREAD

**Issue by maxtacco** [softsimon/ngx-bootrap-multiselect#173]
IMHO, it is kind of strange to add group's parent id to the model when all of its children are selected but you must have a business case for it. Still, it would be nice to make this behavior configurable.

Btw, another use case can be to add JUST a parent id to the model when all of its children are selected.

**Comment by chris--jones** [comment]
Adding both covered the most use cases, you can then filter out the ones you want. 
This should be straightforward to implement though.

**Comment by maxtacco** [comment]
Hi @chris--jones, 
Filtering out is not that straight forward especially if parent and child options are of different types. For example,  In my case I have company / department groupings, but I only need to submit departments. In this case filtering out is doable but I need to keep a reference to the original data structure and then do some post processing before data is sent to a server. But all of this can easily be solved with a config setting.

**Comment by EddPorter** [comment]
I too, would like to see this setting. I only want the user to see the selected children and not the parents. Likewise, I don't want the model to contain the parent. For my use case the parents are meaningless headers used to break up the display of the children.

**Comment by EddPorter** [comment]
As soon as I commented, I figured out I can just set the children's parentId to 0. It seems to work for my purposes.

**Comment by BhavinPatel04** [comment]
Any ETA on this enhancement @chris--jones ?

This would be a good feature. Thanks in advance.
