### ISSUE TITLE
Is there any way I can collapse the child options? 

### ISSUE THREAD

**Issue by Yuanma1224** [softsimon/ngx-bootrap-multiselect#178]
Hello, just wondering what the best way to collapse all the child options on init, I have too many options , it will be nice if I can hide the child options and  only show the parent options,  the user will click the eahc parent option and it will drop down the child options.

thanks!

**Comment by chris--jones** [comment]
This functionality isn't built in, but you could probably manage it with css and some additional js
This assumes you have your parents with isLabel set to true.
e.g.
**js**
```typescript
document.querySelectorAll(".dropdown-header").forEach(header => {
  header.addEventListener("click", event => { var li=event.target.nextSibling; while(li && li.classList && !li.classList.contains("dropdown-header")) { li.style.display=li.style.display==="none"?"block":"none"; li = li.nextSibling; }})
})
```
**css**
```css
li.dropdown-header {
    display: block;
    cursor: pointer;
}
.dropdown-item {
    display: none;
}
```

You could also look at the change event `(ngModelChange)="onChange($event)"` and update your model to dynamically insert and remove the children when a parent is clicked, but this seems more trouble than it's worth.

**Comment by Yuanma1224** [comment]
Hello, thanks for the help, I am very new to angular.
I am just wondering if I can apply a bootstrap collapse class to the options, like use ngIf to  find the parents and add the bootstrap collapse class? 
thanks

**Comment by chris--jones** [comment]
You can't use bootstrap collapse because the parent items in the dropdown are not container elements for the children.
