### ISSUE TITLE
Single select configuration - onChange firing before unselect

### ISSUE THREAD

**Issue by jeremiah-white** [softsimon/ngx-bootrap-multiselect#183]
When using a configuration with selectionLimit=1 and autoUnselect=true, the onChange function passed into the input ngModelChange is fired before the original value is unselected, so the optionsModel ends up with 2 elements in it.  The event is also not fired again when the unselect does occur.

This was found in v1.3.2.

**Comment by chris--jones** [comment]
Similar to #148, I'll test this as part of the fix
