### ISSUE TITLE
Having troubles to import IMultiSelectOption

### ISSUE THREAD

**Issue by tomerpeled** [softsimon/ngx-bootrap-multiselect#188]
I've succeed to load MultiselectDropdownModule but when trying to import the IMultiSelectOption for my component using the following line, it's not working:
`import { IMultiSelectOption } from 'angular-2-dropdown-multiselect';`

What am I missing?

**Comment by nicholasguyett** [comment]
Could you clarify what you mean by "not working"?  If you're getting an error message, please include include it here.

**Comment by tomerpeled** [comment]
IMultiSelectOption is not loaded and I cannot use it in my TypeScript.
If I'm working with "any" instead of IMultiSelectOption I do succeed to work and everything works fine.
But in this way I'm missing the strongly type ability of TypeScript.

**Comment by TeodorKolev** [comment]
same here

**Comment by TeodorKolev** [comment]
It was fix form me when I include 
```
 onChange() {
        console.log(this.optionsModel);
    }
```
