### ISSUE TITLE
HTTP404: Not Found - The server has not found anything matching the requested http:localhost:60029/css/bootstrap-multiselect.css

### ISSUE THREAD

**Issue by animishas** [softsimon/ngx-bootrap-multiselect#189]
I am using Reactive Forms for my angular template. I have followed all the steps mentions. I will upload the pictures. please let me know if I am missing something else? Thanks This is the error I get
![errors](https://cloud.githubusercontent.com/assets/25496038/26606945/3fffadc0-4551-11e7-8bd6-2b1e27bcb8f1.PNG)

On my Component.ts file I have this.
![error1](https://cloud.githubusercontent.com/assets/25496038/26605929/26c3fed2-454d-11e7-95de-4310e58937ad.PNG)
![error2](https://cloud.githubusercontent.com/assets/25496038/26606235/6a2bdb8a-454e-11e7-9244-2bfd85c3644d.PNG)
![error3](https://cloud.githubusercontent.com/assets/25496038/26606236/6b9937e2-454e-11e7-8802-608e3b34f411.PNG)

On my component.html file i have this
![error5](https://cloud.githubusercontent.com/assets/25496038/26605983/541f1326-454d-11e7-91e2-42e449620d15.PNG)

On my app.module.ts file i have this 
![error4](https://cloud.githubusercontent.com/assets/25496038/26606025/8478b982-454d-11e7-8c70-db0147f426e5.PNG)

I have installed the package 
![error6](https://cloud.githubusercontent.com/assets/25496038/26606055/b23a57b8-454d-11e7-9b90-0c543a9e83f6.PNG)

Systemjs.config.js file
![error7](https://cloud.githubusercontent.com/assets/25496038/26606910/174af5a6-4551-11e7-8c59-86e3e3595d8a.PNG)

but still I get that error message. Do you have any idea why its happening? Am I missing something here? Thanks a ton in advance

**Comment by TeodorKolev** [comment]
same here. Mess

**Comment by TeodorKolev** [comment]
It was fix form me when I include 
```
 onChange() {
        console.log(this.optionsModel);
    }
```

**Comment by animishas** [comment]
@TeodorKolev  Thanks for your reply, I tried the onChange but it didnt do anything in my case. i still see the issue. Anyone has tried to implement this and had similar issues? Please help
