### ISSUE TITLE
Cannot read property 'valid' of undefined

### ISSUE THREAD

**Issue by DutchKevv** [softsimon/ngx-bootrap-multiselect#195]
I keep getting the `Cannot read property 'valid' of undefined` error if I start with a model that has preselected values (especially if more then 1 option is preselected)

```
<ss-multiselect-dropdown
			name="instruments"
			[options]="multiSelectOptions"
			[settings]="multiSelectSettings"
			formControlName="instruments"
			[(ngModel)]="model.data.instruments">
</ss-multiselect-dropdown>
```

```
ngOnInit() {
    this.model = new Model({data: { instruments: ['AUD_USD', 'EUR_USD']}});
    this.form = this.formBuilder.group(this.model.data);
}
Cannot read property 'valid' of undefined
```

If i first create an empty model, then create a form with the empty model and then update the data in ngAfterViewInit() it works as expected...

Any hints / tips?

It seems MultiSelect doesn't like the preselected values on init but really can't figure out why!

The (old workaround) code can be found here 

https://github.com/DutchKevv/TradeJS/blob/development/client/app/common/backtest-settings/backtest-settings.component.ts#L50

This has some code to workaround it, but think you an read through it :)

Thanks!

**Comment by ildarnm** [comment]
+1
