### ISSUE TITLE
Updating README with @Input() and @Output() fields

### ISSUE THREAD

**Issue by fmicheloni** [softsimon/ngx-bootrap-multiselect#207]
A small section with the Inputs and Outputs of the directive would be much useful and appreciated!

**Comment by nicholasguyett** [comment]
Is this a common thing in other components?  The README doesn't describe the inputs and outputs with the decorators, but it does show all the inputs and outputs in the usage example.  If you know how Angular binding works, you know what the inputs and outputs are from that.

**Comment by fmicheloni** [comment]
You are right, @Output()s are not important and should not be described. But having a quick reference about what the @Input()s do could be helpful! Just as a quick reference. Usage examples shows deeply the functionalities of a library instead.

**Comment by nicholasguyett** [comment]
It already does provide a quick reference on everything you can do with the inputs.  

It starts here, in the readme
https://github.com/softsimon/angular-2-dropdown-multiselect#settings

**Comment by fmicheloni** [comment]
What about this @Input()?

 @Input() disabled: boolean = false;

Unless you start reading the code you will never be aware of it!

**Comment by nicholasguyett** [comment]
I see...  Those are actually just standard for all Angular input elements.  But I see where you're coming from, it probably would be helpful to specify that we support those, as it isn't always automatic.
