### ISSUE TITLE
Rendering long list of items in dropdown

### ISSUE THREAD

**Issue by karunanaik** [softsimon/ngx-bootrap-multiselect#210]
Following is my code for one of the dropdown that I am using. However, I have noticed that the dropdown takes a while to open up when clicked if there are 1000 something items in the drop down list. I need some suggestions to improve the rendering performance. Any ideas?

```
<div>Site Leader <i *ngIf="isSiteLeaderLoading" class="fa fa-spinner fa-spin"></i></div>
            <ss-multiselect-dropdown [options]="selectOptionsForSiteLeader" [(ngModel)]="optionsModelForSiteLeader"
                                     [texts]="selectTextForSiteLeader"
                                     [settings]="selectSettings"
                                     (ngModelChange)="onChangeSiteLeader($event)"></ss-multiselect-dropdown>
```

**Comment by gund** [comment]
As [this PR](https://github.com/softsimon/angular-2-dropdown-multiselect/pull/202) already merged you can increase performance of your large dropdowns.
I also have submitted [another PR](https://github.com/softsimon/angular-2-dropdown-multiselect/pull/227) that will improve filtering performance.

Stay tuned =)
