### ISSUE TITLE
Reference warnings when building

### ISSUE THREAD

**Issue by nitimmerman** [softsimon/ngx-bootrap-multiselect#212]
Hi @softsimon ,

First of all, Thanks for creation this nice component!
When bundlinng our application with webpack we get three warnings: It seems like you are still referencing files which do not exist anymore:
Could you please remove those references so that this component is warning free?
Here are the warnings:
WARNING in ./~/angular-2-dropdown-multiselect/index.js
(Emitted value instead of an instance of Error) Cannot find source file 'tmp/index.ts': Error: Can't resolve './tmp/index.ts' in .... \node_modules\angular-2-dropdown-multiselect'

WARNING in ./~/angular-2-dropdown-multiselect/dropdown/search-filter.pipe.js
(Emitted value instead of an instance of Error) Cannot find source file '../tmp/dropdown/search-filter.pipe.ts': Error: Can't resolve '../tmp/dropdown/search-filter.pipe.ts in ......\node_modules\angular-2-dropdown-multiselect\dropdown'

WARNING in ./~/angular-2-dropdown-multiselect/dropdown/dropdown.module.js
(Emitted value instead of an instance of Error) Cannot find source file '../tmp/dropdown/dropdown.module.ts': Error: Can't resolve '../tmp/dropdown/dropdown.module.ts' in ......\node_modules\angular-2-dropdown-multiselect\dropdown'

**Comment by gund** [comment]
This is the problem with source maps since they are pointing to the source code that does not ship with the npm library.
So what you can do is just exclude this library from source-map plugin and you will get rid from these warnings.
