### ISSUE TITLE
Disable unselect for default option

### ISSUE THREAD

**Issue by vitaliyzolotoy** [softsimon/ngx-bootrap-multiselect#214]
How to disable unselect for default option?

**Comment by nicholasguyett** [comment]
You want to prevent users from de-selecting the options you set as default?

If so, what exactly is the intent in displaying them if its a non-configurable choice?

**Comment by vitaliyzolotoy** [comment]
> You want to prevent users from de-selecting the options you set as default?

Yes.

> If so, what exactly is the intent in displaying them if its a non-configurable choice?

User can select other options but can't deselect default.

**Comment by nicholasguyett** [comment]
There is currently no way to do that using the current functionality.

I think your use case would be better served by listing the required options separately and merging their selection with your required values in the component, but I suspect @softsimon would accept a pull request for this feature if you were to submit it.

**Comment by Ezeon** [comment]
I think it would be great to have a configurable minimum number of selected items just as we already have a maximum number of selected items. I have the need to for this functionality in my application.

I'll create a pull request for this.

**Comment by softsimon** [comment]
@Ezeon Do that. It will be merged.

**Comment by Ezeon** [comment]
Great. I've created PR #235 for this.
