### ISSUE TITLE
How to reset form containing ss-multiselect-dropdown when using reactive forms module approach

### ISSUE THREAD

**Issue by Gourav102** [softsimon/ngx-bootrap-multiselect#240]
Hi, I am using the reactive forms module approach and I want to reset my form containing ss-multiselect-dropdown. I used reset method on form, but it's giving an error "ORIGINAL EXCEPTION: Cannot read property 'length' of null" (even though this plugin had some values checked inside it). Form was resetting in correct way before adding ss-multiselect-dropdown. Any help would be appreciated to fix this error. Thanks in advance.

**Comment by softsimon** [comment]
You could do:
this.reactiveForm.controls['dropdownComponent'].setValue([], {emitEvent: false});
