### ISSUE TITLE
async pipe does not appear to work when binding to [options]

### ISSUE THREAD

**Issue by benthedeveloper** [softsimon/ngx-bootrap-multiselect#250]
When I try to bind to an Observable like this:
`<ss-multiselect-dropdown [options]="myOptions$ | async" [(ngModel)]="optionsModel" (ngModelChange)="onChange($event)"></ss-multiselect-dropdown>`

And I have myOptions$ assigned to an Observable in a service in my ngOnInit() like this:
`this.myOptions$ = this.testService.options$;`

The options populate in the dropdown when the page first loads, but then say if a new option is added and the observable is updated (like when optionsSource.next() is called in the service), the multi-select dropdown options do not appear to update. I believe this used to work before a recent update to the package...

For now, the workaround is I can subscribe to an Observable and assign the data to myOptions in the success block, and not use the async pipe in the template, and that appears to work, but I don't see why it's not working with the async pipe.

**Comment by nicholasguyett** [comment]
Just to confirm, when you manually subscribe to the observable, it emits correctly, but when you use the async pipe on the same observable it fails?

Are you getting any errors in the console when that happens?

Also, on whim, can you see what happens if you set `this.myOptions$ = this.testService.options$.startWith([])`?

**Comment by benthedeveloper** [comment]
I tested this some more, and it looks like it doesn't work if I manually subscribe to an Observable, or use the async pipe. I'm not getting any errors in the console, and I tried using `this.testService.options$.startWith([])` and that didn't work either.

One thing that did make it work though (both async pipe and manually subscribing) was emitting a copy of the array in the .next() call, like this:
`this.optionsSource.next([...this._options]);`

I built a very basic angular-cli app to test it out, I'm basically just using a button to push a new item onto the array each click, this is what the relevant files look like:

app.module.ts:
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MultiselectDropdownModule } from 'angular-2-dropdown-multiselect';

import { AppComponent } from './app.component';
import { TestService } from './test.service';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    MultiselectDropdownModule
  ],
  providers: [
    TestService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }`

app.component.html:
`<div>
  <h1>{{title}}</h1>

  <div style="margin: 20px 0;">
    <button class="btn btn-primary" (click)="addOption()">Add option to myOptions dropdowns using service</button>
  </div>

  <h2>myoptions$ (async pipe):</h2>    
  <ss-multiselect-dropdown [options]="(myOptions$ | async)" [(ngModel)]="optionsModel" (ngModelChange)="onChange($event)"></ss-multiselect-dropdown>

  <h2>myOptions (no async pipe)</h2>
  <ss-multiselect-dropdown [options]="myOptions" [(ngModel)]="optionsModel" (ngModelChange)="onChange($event)"></ss-multiselect-dropdown>

  <hr>

  <h2>Debug</h2>
  <p>myOptions$ | async:</p>
  <ul>
    <li *ngFor="let option of (myOptions$ | async)">{{ option.name }}</li>
  </ul>

  <p>myOptions:</p>
  <ul>
    <li *ngFor="let option of myOptions">{{ option.name }}</li>
  </ul>

</div>
`
app.component.ts:
`import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/startWith';
import { TestService } from './test.service';
import { IMultiSelectOption } from 'angular-2-dropdown-multiselect';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'Testing angular2-dropdown-multiselect';
  myOptions$: Observable<IMultiSelectOption[]>;
  optionsModel: number[];
  private curId = 1;

  myOptions: IMultiSelectOption[];

  constructor(private testService: TestService) { }

  ngOnInit() {
    // assign directly to Observable for async pipe
    this.myOptions$ = this.testService.options$;

    // subscribe to observable
    this.testService.options$.subscribe((options: any[]) => {
      this.myOptions = options;
      console.log('this.myOptions is now: ', this.myOptions);
    });
  }

  onChange() {
    console.log('this.optionsModel: ', this.optionsModel);
  }

  addOption() {
    this.testService.addOption({
      id: this.curId,
      name: `option ${this.curId}`
    });
    this.curId++;
  }

}
`
test.service.ts:
`import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import { IMultiSelectOption } from 'angular-2-dropdown-multiselect';

@Injectable()
export class TestService {
  private _options: IMultiSelectOption[] = [ { id: 0, name: 'option 0' } ];

  private optionsSource = new BehaviorSubject<IMultiSelectOption[]>(this._options);
  options$ = this.optionsSource.asObservable();

  constructor() { }

  addOption(newOption: IMultiSelectOption) {
    this._options.push(newOption);
    this.optionsSource.next(this._options);
    // this.optionsSource.next([...this._options]);
  }

}
`
