### ISSUE TITLE
Options don't show when deployed to production

### ISSUE THREAD

**Issue by EduardoIbarra** [softsimon/ngx-bootrap-multiselect#252]
I have this ss-multiselect-dropdown perfectly working on my dev environment, grabbing my options from a rest API, but once I run ng build and access my app from its public url, the options don't show. I already checked that the options I pass to [options] are there.

**Comment by softsimon** [comment]
Can you make sure you are running the latest version (1.5.3). There was a bug like this in early 1.5.x

**Comment by EduardoIbarra** [comment]
I've just updated to 1.5.3, now my dev environment is presenting the same problem

**Comment by madthad91** [comment]
Using 1.5.4, and only had this issue before adding the MultiselectDropdownModule module to my main app's module. Please post the steps you followed when adding angular-2-dropdown-multiselect to your project.

**Comment by andrey36101** [comment]
I Have the same issue with "version": "1.5.4" - No options in dropdown, "select all" and "unselect all" works fine, just can't see any options populated in dropdown itself.

**Comment by ggoelles** [comment]
I'm having the same issue. Gone back to 1.4.1. Has a typo in the texts-options but is working well.

**Comment by upreddy** [comment]
I have the same issue, solved by calling updateNumSelected() and updateTitle() functions at https://github.com/softsimon/angular-2-dropdown-multiselect/blob/5947b4d2161192428a997e48312d00d640c0a304/src/dropdown/dropdown.component.ts#L257

Fix:

if (value !== undefined && value !== null) {
            this.model = Array.isArray(value) ? value : [value];
            **this.updateNumSelected(); // Updating num selected
            this.updateTitle(); // Updating title**
        }
        else {
            this.model = [];
        }
