### ISSUE TITLE
Are children supported?

### ISSUE THREAD

**Issue by carlhussey** [softsimon/ngx-bootrap-multiselect#259]
Can I nest my data sets?

```
Country
  State
    [] City
    [] City
    [] City
```

**Comment by nicholasguyett** [comment]
The documentation needs updating but I believe so.

```typescript
export interface IMultiSelectOption {
  id: any;
  name: string;
  isLabel?: boolean;
  parentId?: any;
  params?: any;
  classes?: string;
}
```

If you set the parentId value of the child elements, I believe it will do what you expect it to.  If not, respond here to let me know.

**Comment by softsimon** [comment]
There is only one level of nesting. Parent (labels) with children.
