### ISSUE TITLE
How to configure in systemjs.config.js ?

### ISSUE THREAD

**Issue by vijilvs** [softsimon/ngx-bootrap-multiselect#260]
I  got the error like this while running the application >
![image](https://user-images.githubusercontent.com/31234967/29551440-5a29a8f6-8730-11e7-9499-9f5586d40df3.png)

These are the steps i have done >
**In app.module.ts >**

![image](https://user-images.githubusercontent.com/31234967/29551506-9b96b2a2-8730-11e7-88d6-716975c140f2.png)

**In app.component.ts >**
![image](https://user-images.githubusercontent.com/31234967/29551532-c46511f6-8730-11e7-8355-aa6b6d0ef431.png)

And
In systemjs.config.js file > 
 map section > 'angular-2-dropdown-multiselect': 'node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.js'

packages section > 'angular-2-dropdown-multiselect': {
          main: 'index.js',
          defaultExtension : "js"
      }

I found some issue like , after installation there is not such path/folder mentioned in map section
![image](https://user-images.githubusercontent.com/31234967/29551818-3bb62b86-8732-11e7-8354-a93ce90f75ee.png)

This is angular-2-dropdown-multiselect installation log
![image](https://user-images.githubusercontent.com/31234967/29552024-18f9294e-8733-11e7-89d5-e2b22762ba61.png)

Can anyone help me to resolve this issue ?

**Comment by natcohen** [comment]
You need to add this: `'angular-2-dropdown-multiselect': 'npm:angular-2-dropdown-multiselect/bundles/dropdown.umd.js',` to your systemjs.config.js.

If you have questions or need help use stackoverflow not github!
