### ISSUE TITLE
Open dropdown dynamicaly

### ISSUE THREAD

**Issue by vitaliyzolotoy** [softsimon/ngx-bootrap-multiselect#265]
Is there any way to open dropdown dynamically?

**Comment by edwardsmatt** [comment]
I have used something like this with success:

```
const element  = this.elementRef.nativeElement.querySelector(`#multiselect_field > div > button`)
element.click();
```

**Comment by thebf** [comment]
Could you go into a bit more detail?

**Comment by edwardsmatt** [comment]
Essentially, I have used the selector for the Button inside the dropdown (the one which display's the title), and triggered a click event. 

`elementRef` is an instance of ElementRef injected into my Angular Component.

This is triggered by another event on the screen (in my case a selection in a different drop down).

I'll try and put together a demo over the next couple of days to help provide clarity.

**Comment by gund** [comment]
You can just get a reference to drop-down component via `@ViewChild` and then call `(toggleDropdown())[https://github.com/softsimon/angular-2-dropdown-multiselect/blob/b68d7e34c45dbc148cb7a6d0efd9ca53d18f0482/src/dropdown/dropdown.component.ts#L312]` method.

**Comment by thebf** [comment]
@gund I tried it. The method is executed but conflicts with the closeOnClickOutside setting.
Any suggestions for avoiding this?
If a good solution to the collision is found, this would be a great way of solving this.

**Comment by gund** [comment]
@thebf can you please explain what do you mean by conflicting?

Because it's essentially the same thing you are calling just by clicking on the button.

**Comment by thebf** [comment]
After toggleDropDown is called the code below is called and closes the drop down immediately.
`
  @HostListener('document: click', ['$event.target'])
  @HostListener('document: touchstart', ['$event.target'])
  onClick(target: HTMLElement) {
    if (!this.isVisible || !this.settings.closeOnClickOutside) return;
    let parentFound = false;
    while (target != null && !parentFound) {
      if (target === this.element.nativeElement) {
        parentFound = true;
      }
      target = target.parentElement;
    }
    if (!parentFound) {
      this.isVisible = false;
      this.dropdownClosed.emit();
    }
  }
`

**Comment by gund** [comment]
I assume that is because you are clicking on some other button to toggle this drop-down.

So the solution can be to call toggle method in the next JS tick (like in setTimeot(0)).

It should wait for that click handler to complete and than open drop-down

**Comment by thebf** [comment]
@gund That works for the first two clicks but not after for some reason I can't comprehend.

**Comment by gund** [comment]
Would you be able to create plunkr so I can have a look?

**Comment by thebf** [comment]
@gund Thank you for putting me on a good track
setTimeout(() => this.multiselectDropdown.externalToggleDropdown(), 0); worked just fine
setTimeout(this.multiselectDropdown.toggleDropdown(),1000); did not work.

Though, a good implementation of the override bit i hacked together would allow for a good solution to the use case described here:
https://github.com/softsimon/angular-2-dropdown-multiselect/issues/341

**Comment by gund** [comment]
@thebf just came idea that instead of using `setTimeout()` you can actually `stopPropagation()` on your click and then normal `toggleDropdown()` method will work perfectly (well should, in theory... =)

**Comment by thebf** [comment]
@gund That had the side-effect of blocking the intended use of closeOnClickOutside when you have multiple and you click on another button with this property.

**Comment by thebf** [comment]
Even the timeout one has issues when I try test it in depth. there is some weird behavior when the dialogue is already open it does not close when the custom button is clicked.
I prettied up the override code and will suggest it in a PR
It will allow for a custom container that can access any internal function without opening/closing the dialogue, while only requiring the implementer of the custom container to add one line of code before the function call the function-wrapper: 
`
this.multiselectDropdown.overrideAutoClose = true;
this.multiselectDropdown.toggleDropdown();
`
For opening/closing the Dropdown with a custom button
`
this.multiselectDropdown.overrideAutoClose = true;
this.multiselectDropdown.checkAll();
`
For checking all with a custom button

**Comment by gund** [comment]
@thebf I'm now quite lost of what are you talking about, especially with checkboxes.
I thought we were talking just about opening a dropdown from the external UI element.

So as I said above - I did small demo which proves that prevent default is sufficient for that: https://angular-dropdown-example.stackblitz.io

To check out code - [follow here](https://stackblitz.com/edit/angular-dropdown-example).

**Comment by thebf** [comment]
Click two of the Toggle drop down buttons. You will see the autoclose will not function as inteded with the stopPropagation approach.
