### ISSUE TITLE
Adding background color to checked items

### ISSUE THREAD

**Issue by bankszorsqt** [softsimon/ngx-bootrap-multiselect#267]
Is there "easy" way to add a background color to selected items in the dropdown? If no, it would be very cool option to have.

**Comment by thebf** [comment]
I sort of have this working on my local modification, I haven't found a way of disabling the hover color from bootstrap which means that the row being hovered over is always grey.

Anyone have a good suggestion for how this could be done?

**Comment by thebf** [comment]
I figured out how ,had to read a bit of bootstrap documentation. Will put together a pull request for this today or tomorrow.
