### ISSUE TITLE
how to get id and name for a selected value in model

### ISSUE THREAD

**Issue by frontend123** [softsimon/ngx-bootrap-multiselect#269]
I am trying to get id and name for a selected value in single select drop down model.

`this.myOptions = [
      { id: 1, name: 'Option 1' },
      { id: 2, name: 'Option 2' },
    ];`
` console.log(this.optionsModel);`
for e.g if I select Option 1 from drop down i need to get id:1 and name:Option 1 both values in OptionsModel.

**Comment by Bank5z0rSqt** [comment]
I tried many ways, I always get Id value/values, as an array of numbers, how do I get the array of names or whole objects? Ofc I can filter through `this.optionsModel` and search by id, but is there some "out of the box" way? With all those other fancy options I feel like there should be some "easy" way, otherwise, it's all wasted.

**Comment by gsaxam** [comment]
+1

**Comment by tobiamos** [comment]
+1

**Comment by gsaxam** [comment]
I got this done by appending the value of the `name` field within `id` itself. For my implementation, when I am building the `this.myOptions` array, I am populating it in this way:

`this.myOptions = [ { id: 1===myValue1, name: 'myValue1' }, { id: 2===myValue2, name: 'myValue2' }, ];`

and later, you can do a split("===") on the `id field` to get both id and value.

Not the best implementation one can use, but it works!

**Comment by gund** [comment]
The thing is current implementation does return only selected id's.
I agree that selecting whole objects makes more sense but this change will be breaking.

So if we will consider implementing it the best option would be to enable it under the setting flag.
@softsimon what do you think about it?

**Comment by gund** [comment]
Btw I just realized how you can easily achieve this behavior without too much "hacking" (though I did not test it yet but should work fine).

When you get your array of options, just update it once to set each item's id to itself like so:
```ts
const myOptions = [{id: 1, name: 'Option #1'},...];

// One time post-processing on options
myOptions.forEach(obj => {
  obj._id = obj.id // You might want to save original id
  obj.id = obj;
});
```

And in this case you will get selected items as objects and then you can access stored real id `selectedOption._id`
