### ISSUE TITLE
Select all checkboxes on page load and report on changes made to it

### ISSUE THREAD

**Issue by gsaxam** [softsimon/ngx-bootrap-multiselect#276]
Hi,

I am planning to use the plugin in a slightly different manner. In my case, all of the rendered checkbox must be "checked" on page load and if the user "unchecks" anything, it should be reported. 

Any ideas on how I can get this done?

**Comment by softsimon** [comment]
* Prefill the optionsModel array with all the IDs from your dropdown items id's 
* Use the default ngModelChange event to be notified of changes

`model: [1,2,3,4,5];

(ngModelChange)="onChange($event)"`

**Comment by gsaxam** [comment]
I am dynamically loading contents from elasticsearch so the number of ids will change everyday. Is there a way to define all ids without listing them one by one manually?

**Comment by softsimon** [comment]
Why manually. Just map out the id's from the content
options = fromElasticSearch
model = options.map((option) => option.id);

**Comment by gsaxam** [comment]
OK, but a small issue with this is when I uncheck a checked box, it prints out the whole array of all ids just without the recently unchecked one. Is there a way the `optionsModel` array can only show the changed ones (user clicked) and ignore the checked ones (by default) on pageLoad?
