### ISSUE TITLE
PullRight option KO with bootstrap 4.0.0-beta

### ISSUE THREAD

**Issue by janbomber** [softsimon/ngx-bootrap-multiselect#277]
Hi
_.dropdown-menu-right_ class was removed in the lastest bootstrap version (4.0.0-beta).
so _pullRight_ option does not work with this bootstrap version

**Comment by softsimon** [comment]
The .dropdown-menu-right class is not removed in 4.0 beta, but the positioning is now done with JavaScript.

**Comment by rashnk** [comment]
pullRight not working,
bootstrap 4.0.0
```
 multiselectSettings: IMultiSelectSettings = {
    enableSearch: false,
    pullRight:true ,
    // checkedStyle: 'fontawesome',
    buttonClasses: 'btn btn-default btn-block',
    dynamicTitleMaxItems: 0,
    displayAllSelectedText: false,
    maxHeight: '200px',
    
  };
```
