### ISSUE TITLE
Using multiple dropdowns

### ISSUE THREAD

**Issue by gsaxam** [softsimon/ngx-bootrap-multiselect#278]
I am trying to use more than 5 dropdowns. Should I create an `optionsModel` for each dropdown and give it their own variable names? By doing that, I would not know how to call the proper optionsModel for the actual dropdown being changed. Since the name `optionsModel` would be different for each dropdowns.

```
onChange() {
        console.log(this.optionsModel);   // <---- This would not work anymore
    }
```

**Comment by pmadhavan** [comment]
I too need to add 3 drop-downs next to each other. Any luck finding a way to achieve it?

**Comment by pmadhavan** [comment]
I achieved it by creating seperate components for each dropdown.
