### ISSUE TITLE
 package author has not included the right index files etc so npm can load the ts using the shorthand notation.

### ISSUE THREAD

**Issue by Vishalckc** [softsimon/ngx-bootrap-multiselect#286]
1) package author has not included the right index files etc so npm can load the ts using the shorthand notation.

2) Documentation dosent seems correct eg:
the README says MultiselectDropdownModule, but I think it's a typo and should be MultiselectDropdown

**Comment by thebf** [comment]
2. I implemented this package in my local test-application. importing MultiselectDropdownModule worked just fine in the app.module.ts file
The actual component you build should work with IMultiSelectOption, IMultiSelectTexts, IMultiSelectSettings imported.
