### ISSUE TITLE
How change width of button and popup menu?

### ISSUE THREAD

**Issue by jouma80** [softsimon/ngx-bootrap-multiselect#290]
I try to change the width of button by adding css style :
styles :['.btn-width {width:100%} ']
and add it to property
 buttonClasses: 'btn btn-default btn-secondary btn-width',
but Not Work

**Comment by PizzaPokerGuy** [comment]
You need to set custom settings: Ex below.
this.mySettings = {
      enableSearch: false,
      checkedStyle: 'fontawesome',
      **buttonClasses: 'btn btn-outline-primary btn-block',
      containerClasses: 'btn-block',
      itemClasses: ' ml-2 ',**
      dynamicTitleMaxItems: 3,
      displayAllSelectedText: true
  };
