### ISSUE TITLE
Show all the selected values on hover of the drop down filed as tool-tip.

### ISSUE THREAD

**Issue by frontend123** [softsimon/ngx-bootrap-multiselect#296]
Is there a way to show all the selected values in a tool tip when we hover on the drop down filed ?

**Comment by iliangogov** [comment]
I need to use it this way as well

**Comment by frontend123** [comment]
Did any one tried this one? current scenario it is showing number of items selected after 3 selection. Need to show all selected items text in a tool tip on hover.

**Comment by anandSep90** [comment]
am also facing the same challenge. Is there any way to implement the tool tip with selected values?
