### ISSUE TITLE
Unable: Remove selected value

### ISSUE THREAD

**Issue by tungphien** [softsimon/ngx-bootrap-multiselect#300]
Hi @softsimon 

I have see an error when include angular-2-dropdown-multiselect. 
My case: In function onChangeReleaseVersion, I set model of select to empty, BUT the selected not clear for me
![capture](https://user-images.githubusercontent.com/28994477/31381009-5e2d92ea-addd-11e7-9002-b5e79c97fa04.PNG)

Please give solutions for this

Thanks

HTML:
<ss-multiselect-dropdown [options]="repos" [ngModel]="reposModel" [texts]="myTexts" [settings]="mySettings"  (ngModelChange)="onRepoChange($event)" ></ss-multiselect-dropdown>

In function:
onChangeReleaseVersion(item) {
        this.reposModel = [];    
}

and  
onRepoChange(newValue) {
        this.reposModel=newValue;
}

**Comment by moogiio** [comment]
Got the same problem, still looking for a viable solution.

**Comment by Un1xMida** [comment]
am facing the same problem too and couldn't see any solutions for it

**Comment by Un1xMida** [comment]
finally found an work around 
in your component HTML
- add [(ngModel)]="optionsModel" to the <ss-multiselect-dropdown> tag
- add (ngModelChange)="onChange($event)" to the <ss-multiselect-dropdown> tag

in your component TS
- add optionsModel: number[];
- add this function 
  onChange() {
    document.getElementsByClassName('YOUR_BUTTON_CLASS_NAME')[0].textContent = '  ';
  }

happy hacking =)
