### ISSUE TITLE
Validation problem

### ISSUE THREAD

**Issue by iRodchenkov** [softsimon/ngx-bootrap-multiselect#302]
Hi!

When I use dropdown with ngModel, control is always _touched_ (before any user actions)

```
<form #editorForm="ngForm">
	...
	<ss-multiselect-dropdown 
		[options]="regions" [(ngModel)]="selectedRegions" [texts]="texts" 
	[settings]="settings" name="selectedRegions" required></ss-multiselect-dropdown>
	<div *ngIf="editorForm.form.controls.selectedRegions?.touched && editorForm.form.controls.selectedRegions?.errors?.required" class="alert alert-danger">
		Error!
	</div>
	...
</form>
```

So I get validation message right after the form is loaded.

Is it a bug?

Thanks!

P.s. it started when I upgraded version from 1.0.2 to 1.6.0

**Comment by kziemianek** [comment]
Tried to reproduce Your problem but without a success
https://stackblitz.com/edit/angular-dya6xv

Can You provide working example ?

**Comment by iRodchenkov** [comment]
Hi!
Thank you for responding

I missed one important thing: in my application I get regions from the server. Here I've just added _setTimeout_ to yous example.
https://stackblitz.com/edit/angular-d4skmt

And one more thing. In you example dropdown becomes _touched_ only after it's value is changed (it always becomes _touched_ and _dirty_ at the same time). But it should become _touched_ when it loses a focus at the first time. Here you can see the differece between this dropdown control and a default select:
https://stackblitz.com/edit/angular-iwehra

**Comment by kareljuricka** [comment]
Same problem here. 

@iRodchenkov I use workaround: with custom directive on multiselect I use DI to get ngControl of item. Then I just take 

```
this.ngControl.valueChanges
            .first()
            .subscribe((value) => {
                this.ngControl.control.markAsPristine();
                this.ngControl.control.updateValueAndValidity();
            });
```

**Comment by AmbroseChase** [comment]
I have the same issue here too. 

There's any default definitive solution?

Hey @kareljuricka, could you be more specific about your workaround? How is this custom directive of yours? Could you show more of the  code?
