### ISSUE TITLE
ngModel property is updated when options of dropdown are changed

### ISSUE THREAD

**Issue by BlindDespair** [softsimon/ngx-bootrap-multiselect#303]
When you have let's say 2 dropdowns and the content of the second dropdown depends on selection from first dropdown and you want to empty the value of selection of dropdown2 in case it's not present in new options, the whole thing breaks, because dropdown still resets it back to the previous value. ngModel **should not** be updated by update of any other property of component. This is causing a lot of trouble trying to work it around. I'd be grateful if this will be fixed.

**Comment by gund** [comment]
@BlindDespair can you please provide a plunkr with exact use-case because I'm using this control in this kind of scenario (where 2-3 fields are depending on each other's selection and update self values accordingly) and having absolutely no problems with this...

Thanks

**Comment by BlindDespair** [comment]
Okay, so I did more investigation and played with plunker. It turned out that it's only broken in 1.6 version(last I think). I checked it with 1.5.4 and there it works correctly. Here is plunker link so you can check it out yourself: https://plnkr.co/edit/KCIYJSDrXv7okaQINzFe?p=preview
Last saved version is using dropdown 1.6. If you select another country and check console you will understand what is going on. Then you can switch to previous version which is using dropdown 1.5.4 and see how it behaves correctly. I hope this will help you!

**Comment by mdigital-demo** [comment]
Thank you @BlindDespair , you saved me a lot of time! 

I can indeed confirm that it works with 1.5.4. I actually load it from a regular dropdown so the issue is not that 2 of these can't work together, it's just the updating of the model.

**Comment by kareljuricka** [comment]
Confirm that 1.5.4 works but newest 1.6.1 still has a bug. I noticed that after initialization of multiselect there are two triggers. One with an undefined value and one with an empty array. In 1.5.4 is only called trigger with an undefined value and it can be easily filtered. But in 1.6.0 and 1.6.1 is also called trigger with an empty array which is hard to filter because it's the same situation like when all options are deselected.

**Comment by thecp** [comment]
> ngModel should not be updated by update of any other property of component

**Comment by martin-g** [comment]
Just to add that we have faced this bug as well. 1.5.4 works fine!
During my debug session I've found that after setting values to `this.model` in ngOnInit the widget will call `ngModelChange` with `this.model` being `[]` again.

**Comment by martin-g** [comment]
I do not see any related change in the recent commits but it seems the bug is gone for me in 1.8.0!
