### ISSUE TITLE
Items are not selected when model is changed in the background

### ISSUE THREAD

**Issue by lubomir-sokolovsky-sde** [softsimon/ngx-bootrap-multiselect#304]
I have a project where each user can store his/her pre-defined filter. When logging again into the application, their filter should be loaded. Here is the code:

```
<ss-multiselect-dropdown [options]="projectsSource()" [(ngModel)]="selectedProjectIds"></ss-multiselect-dropdown>

...

private selectedProjectIds: number[];

constructor(private http: Http){

}

ngOnInit() {
    this.setUserFilter();
}

private setUserFilter(): void {
    const url = Constants.userFilterUrl;
    this.http.get(url).toPromise().then((response) => {
         this.selectedProjectIds = response.json() as number[] || [];
         console.log("Success", this.selectedProjectIds);
    }).catch((error) => {
        console.log("Error", error);
    });
}
```

I can see in the console the message "Success" and an array of numbers. However, the items in the dropdown are not selected. I tried to pre-define the model statically, by setting 
```
private selectedProjectIds: number[] = [1, 2, 3];
``` 

This worked perfectly. The problem is I need to update the model based on user interaction. Is there a way how to achieve this behavior? Or is this a bug/missing feature?

**Comment by lubomir-sokolovsky-sde** [comment]
I have investigated the issue further and it seems as if the dropdown was overwriting the values loaded from the backend service. I have added a `console.log` statement at the beginning of each lifecycle method. Here is the result:

![chromeconsole](https://user-images.githubusercontent.com/16575307/31930996-f998bcd6-b8a1-11e7-99f2-45de900ff1fb.PNG)

It seems that somewhere between `ngAfterContentChecked `and `ngAfterViewChecked `the model is erased and replaced by an empty array.

**Comment by fusionbeam** [comment]
same issue here.
looks like there is no two-way binding for ngModel. that is, setting or changing the ngModel does not set/change the control selections

**Comment by benthedeveloper** [comment]
I'm running into the same issue. I'm getting some data from the backend, and trying to pre-select all values when the component initializes, but the ngModel is getting overwritten with an empty array. Is there any workaround for this?

**Comment by martinkrol** [comment]
I had the same problem so i've used this workaround:

I acessed the dropdown component using @ViewChild:
`@ViewChild('myDropDown') myDropDown: MultiselectDropdown;`

and updated the dropdown's model manually
`this.myDown.model = updatedModel;`

Ps.
Remember to declare the dropdown as a template variable like this:
`<ss-multiselect-dropdown **#myDropDown** [settings]="mySettings" [options]="myOptions" [(ngModel)]="myModel"></ss-multiselect-dropdown>`

**Comment by n83** [comment]
I'm also running into this trying to use the dropdown with reactive forms.  The prepopulation works if I do it as soon as the form object is created, but I get the empty array bug if I try to fetch data from the server and use patchvalue to update the dropdown.  A fix for this would be awesome.

**Comment by anandSep90** [comment]
I also facing same kind of issue.  I need bind the drop-down values dynamically from database. So on ngInit I binded the data and need the show the selected drop-downs. But checkbox is not selected for the passed values in  ngModels property variable

**Comment by kdserg** [comment]
I had the same problem so i've used this workaround:


```
<ss-multiselect-dropdown [options]="localidades" [settings]="dropDownSettings"
 [(ngModel)]="grupo.localidadesIds" name="localidadesIds"></ss-multiselect-dropdown>

...

grupo: any = { id: number, nombre: string, localidadesIds: number[] };
localidades : IMultiSelectOption[] = []; 

constructor(private lS: LocalidadesService,
              private gLS: GruposLocalidadesService){

}

let origenes = [];
    if (this.grupo.id){
      origenes.push(this.lS.getLocalidades());
      origenes.push(this.lS.getLocalidadesSinGrupo());
      origenes.push(this.gLS.getGrupo(this.grupo.id));
    }
    else
    {
      origenes.push(this.lS.getLocalidadesSinGrupo());
    }
Observable.forkJoin(origenes).subscribe(res => {
      if (this.grupo.id) {
        let locs = res[0]; //todas las localidades
        locs = this.mapearLocalidades(locs);
        let locsSG : IMultiSelectOption[]= this.mapearLocalidades(res[1]);
        locs = locs.filter((l:any)=> {return res[2].localidadesIds.indexOf(l.id) >= 0}); 
        locs.forEach((element : any)=> locsSG.unshift(element));
        this.localidades = locsSG;        
        
       //// HERE IS THE TRICK ////

        setTimeout(() => {
          this.setGrupo(res[2]);  
        }, 10);   

////////////////////////////////////     
      }
      else
      {
        let locs = res[0];
        this.localidades = this.mapearLocalidades(locs);
      }
    }, error => {
        if (error.status == 404)
            this.router.navigate(["/notfound"])
    });
  }

  mapearLocalidades(locs: any[]){
    return locs.map((item:any, index:any) => ({id: item.id, name: item.nombre}));
  }

  setGrupo(grupo:saveGrupoLocalidad){
    this.grupo.id = grupo.id;
    this.grupo.nombre = grupo.nombre;
    this.grupo.localidadesIds = grupo.localidadesIds;    
  }
```
