### ISSUE TITLE
publishing app throws the following error with Angular 4.4.6 & webpack 3.8.1

### ISSUE THREAD

**Issue by noumanbhatti** [softsimon/ngx-bootrap-multiselect#309]
I tried to publish the app using dotnet publish -c release and webpack thorws the following error.

 

> ERROR in ./$$_gendir/node_modules/angular-2-dropdown-multiselect/dropdown/dropdown.component.ngfactory.ts
      Module parse failed: Unexpected token (14:32)
      You may need an appropriate loader to handle this file type.
      | import * as i3 from 'angular-2-dropdown-multiselect/dropdown/dropdown.component';
      | import * as i4 from 'angular-2-dropdown-multiselect/dropdown/search-filter.pipe';
      | const styles_MultiselectDropdown:any[] = ['a[_ngcontent-%COMP%] {  outline: none !important;}.dropdown-inline[_ngcontent-%COMP%] {  display: inline-block;}.dropdown-toggle[_ngcontent-%COMP%]   .caret[_ngcontent-%COMP%] {  margin-left: 4px;  white-space: nowrap;  display: inline-block;}'];
      | export const RenderType_MultiselectDropdown:i0.RendererType2 = i0.╔Ácrt({encapsulation:0,
      |     styles:styles_MultiselectDropdown,data:{}});
       @ ./$$_gendir/ClientApp/app/components/ticket/tickettype/tickettype-edit.component.ngfactory.ts 12:0-132
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

**Comment by janega** [comment]
does it work if you do ng build --prod --aot

**Comment by chris--jones** [comment]
This is likely a problem with your webpack configuration rather than this component...
