### ISSUE TITLE
Pre-filled [(ngModel)] throws an error - Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by artem-galas** [softsimon/ngx-bootrap-multiselect#31]
When I pre-fill `[(ngModel)]` for example like this `constructor () {this.selectedOptions = [1,2];}`, 
I am getting this error -  `Cannot read property 'filter' of undefined`, screenshoot - http://joxi.ru/vAWexn5sZbQxmW
Here is how my template and class are looking like this:

```js
// I tried public
private selectedOptions:number[];
  constructor () {
    this.selectedOptions = [1,2];
  }
```
```html
 <ss-multiselect-dropdown [options]="clients" [settings]="{enableSearch: true}"
                                             [(ngModel)]="selectedOptions"
                                             [ngModelOptions]="{standalone: true}"
                                             (ngModelChange)="onChangeClient($event)">
</ss-multiselect-dropdown>
```

I would be grateful if you help me .

**Comment by gsabreu** [comment]
I have the same problem...  I would be grateful if help us.

**Comment by sayedrakib** [comment]
I had also kind of similar problem 'Cannot read property 'filter' of undefined'. My template were not loading the options/values defined in the component class and when I click on the dropdown btn, it shows the error. with my example, check property name(countries) in component class and property binding name(countries) in template. 

In Component class---
`  private **countries**: IMultiSelectOption[] = [
		{ id: 1, name: 'Sweden' },
		{ id: 2, name: 'Norway' },
		{ id: 3, name: 'Denmark' },
		{ id: 4, name: 'Finland' },
  ];`

In template---
`<ss-multiselect-dropdown [options]=**"countries"**></ss-multiselect-dropdown>`

**Comment by thehashrocket** [comment]
@sayedrakib I'm trying it the way you suggested but still getting the same error?

`  private countries: IMultiSelectOption[] = [ { id: 1, name: 'Sweden' }, { id: 2, name: 'Norway' }, { id: 3, name: 'Denmark' }, { id: 4, name: 'Finland' }, ];
`

and then:

`      <ss-multiselect-dropdown [options]="countries"></ss-multiselect-dropdown>
`

![angularapps](https://cloud.githubusercontent.com/assets/342353/21719530/9946d274-d3db-11e6-9bcd-1a7e277e88c7.png)

I'm using angular 2.4 with angular-cli 2.4.1

**Comment by softsimon** [comment]
Are you using both [(ngMode)] and [options] with variables which contains values or at least are empty arrays? Without [(ngModel)] or formControlName there is no functionality.

**Comment by jensbodal** [comment]
In the example you have on github pages there is no ngModel for the the first few options, so maybe I'm not understanding what you mean by no functionality.

https://github.com/softsimon/angular-2-dropdown-multiselect/blob/gh-pages/src/app.component.ts

**Comment by chris--jones** [comment]
@jensbodal I think Simon is saying that the control is not useful without the ngModel, since there's no other way to obtain the selected items.

Looking through the code model and options null checks are intermittent, so I'll have a look at correcting this one way or the other as it's a recurring issue for many people.

For this control to be useful without an ngModel binding there should be a change event to bind to so that you can handle this manually.

**Comment by vithubati** [comment]
I would like to know this issue has a fix because I was trying to pre-select values but got the same error. Would appreciate if anyone could find any different approach to pre-select items in the multi-select box.
thanks
