### ISSUE TITLE
searchMaxLimit > 0 causes options to be queried to exclude one of the options

### ISSUE THREAD

**Issue by LaniMoo** [softsimon/ngx-bootrap-multiselect#315]
1. Set searchMaxLimit to something greater than 0 but less then the number of options
2. Type in each possible option in the search box

Result:
One of the options will not be found.

You can try this by trying to search for "blue" in this plunker:
https://plnkr.co/edit/WTadkY5A4dgXXzdvZcBe?p=preview

I've provided a workaround to this by changing Line 23 of search-filter.pipe.js to the following:
`if (prevResults && prevStr !== '') {`

**Comment by LaniMoo** [comment]
Update: My workaround actually does not work... Any suggestions on how to get around this bug in the meantime?

**Comment by gund** [comment]
I just tried to add one more group and in there all items were searchable.
It's only skipping the first item in the first group...
