### ISSUE TITLE
Set/Remove new options bind change parent for group.

### ISSUE THREAD

**Issue by demo-igor** [softsimon/ngx-bootrap-multiselect#319]
I found something strange when I add some options to the select. My form triggers that form data was changed but I see that form data doesn't change
Could you please help me to understand how it can be fixed.

it looks like it is because of this line:
https://github.com/softsimon/angular-2-dropdown-multiselect/blob/5d692b121d5ff423c3ce5f104a6c1b56d3dea175/src/dropdown/dropdown.component.ts#L226

**Comment by softsimon** [comment]
Have you tried with v1.6.1 which was published just an hour ago?

**Comment by demo-igor** [comment]
Yeah. I use latest version. I see the problem when I added options to the select. 
It looks like `this.fireModelChange(); ` send to FormGroup that data changed. But it is not try because I don't select any option. Just set option to select box

**Comment by demo-igor** [comment]
`    this.productForm.valueChanges.subscribe(() => {
      this.isProductFormChanged = true;
    });
`
In my case after I add options to the select. `isProductFormChanged` set to TRUE.

**Comment by puppeteer701** [comment]
@demo-igor did you found a solution for this issue?

**Comment by demo-igor** [comment]
@puppeteer701 I decided to don't use `this.isProductFormChanged`. Instead of this I compare to JSONs (old form data and new form data) in `canDeactivate`
```
  public canDeactivate(): Observable<boolean> | Promise<boolean> | boolean {
    if (JSON.stringify(this.organizationFormValue) === JSON.stringify(new OrganizationModel(this.organizationForm.value))) {
      return true;
    }
```
