### ISSUE TITLE
angular-2-dropdown-multiselect not working inside formArray

### ISSUE THREAD

**Issue by nileshv123** [softsimon/ngx-bootrap-multiselect#323]
I am using a reactive form, in which there is a FormArray control for the list of students. Each item in the list of students, is a formGroup, which contains a simple formControl to hold an array of numbers. Each number is associated with one hobby.
In Html file, I iterate over the list of students using *ngFor. Each item in the list contains a select box for hobbies. I am using this angular-2-dropdown-multiselect for hobbies. But it is not showing options when I click. It is working well for a simple form control, outside FormArray. But in case of FormArray it is not working.

HTML file.
```
<div class="form-group" formArrayName="students">
  <ul>
    <li *ngFor="let student of this.form.get('students').value; let i=index"  [formGroupName]="i">
      <a (click)="removeStudent(i)">X</a>
      <a> {{ student.name }} </a>
      <ss-multiselect-dropdown [options]="hobbies" formControlName="hobbies"></ss-multiselect-dropdown>
    </li>
  </ul>
</div>
```
Component
```
this.form = this.formBuilder.group({
  students: this.formBuilder.array([ ]),
});
```
Each item in array has this.
```
this.formBuilder.group({
  name: '',
  hobbies: '' // using multiselect dropdown for it.
});
```

**Comment by ajayeh** [comment]
did you get any solution for this issue.
