### ISSUE TITLE
[lazy load] no results

### ISSUE THREAD

**Issue by guidosreis** [softsimon/ngx-bootrap-multiselect#324]
Hi,
When search for something that doesn't exists in lazy load select, result in a infinite Loading, as you can check in the plunkr example.

Is there a way to show "No results found", instead?

**Comment by thebf** [comment]
searchEmptyResult: 'No results found' in your IMultiSelectTexts objects being passed in would achieve this though there is really no current visual indication of a request life cycle feedback as far as I can tell.

**Comment by GregKass** [comment]
Here's a sample working Plunker:

https://plnkr.co/edit/fsZHbth4kzLI79hohcMG?p=preview

You cannot simply change just `searchEmptyResult`. The `onChanges` will only trigger on an object mutation, and reassigning just a member of an object would not be considered a mutation of the object. You must reassign the whole of `myTexts`.
