### ISSUE TITLE
Angular 4 dependency

### ISSUE THREAD

**Issue by gmklaus** [softsimon/ngx-bootrap-multiselect#345]
When I install with 
`
npm install angular-2-dropdown-multiselect --save
`
I get 
```
+-- UNMET PEER DEPENDENCY @angular/common@5.0.3
+-- UNMET PEER DEPENDENCY @angular/core@5.0.3
+-- UNMET PEER DEPENDENCY @angular/forms@5.0.3
`-- angular-2-dropdown-multiselect@1.6.3

```
I know Angular 5 was only released a month and a half ago, but I'm wondering what your plans are for upgrading the dependency.

**Comment by compeek** [comment]
Is there any workaround for using this with Angular 5? I cannot seem to get past the peer dependency errors.

**Comment by janbomber** [comment]
any news?
