### ISSUE TITLE
Next Major Update

### ISSUE THREAD

**Issue by gund** [softsimon/ngx-bootrap-multiselect#349]
Hi all,

It's been a great journey seeing how this component started it's life and evolved over time thanks to all those who contributed to it.

As it was growing it eventually accumulated a bit of mess here and there but we did not really took a stop and cleared it up. So i guess it would be a good time to do that for the next major release.

I want to bring this into discussion here so we can make next version the best we can.

First of all, what I observed is that components template became really complex and concerned with too many things and the reason for that is because it was lacking enough extensibility in the first place.

For example: we have four different styles of displaying items (checkboxes, glyphicon, fontawesome, visual). But these are just details and really may and will be different for each user.

So it makes sense to allow user to provide it's own template for the item - this will bring simplicity and maintainability on our side + ease of extensibility for consumers.

And this improvement can be taken to different parts of component, for example: 
- toggle button
- search field
- buttons check/uncheck all

It will also allow for easier translation of those parts and also styling them will be much easier because user can have direct access to template.

@softsimon @GregKass @chris--jones @nicholasguyett would be great great to have your input on this =)

P.S. Also #254 can be addressed as part of next release

**Comment by thebf** [comment]
Some sort of template library where presets can be provided by the community would allow for extensibility while also allowing for the different templates to be used as easily as they currently are.

Would there be a noticeable performance hit compared to the current approach by loading templates externally?

**Comment by gund** [comment]
Regarding performance - I don't think there will be any problems if done right with change-detection.

And template presets sounds really exciting but I cannot imagine how exactly it could be implemented.
So for I thought to just expose a few inputs that can accept `TemplateRef`s and be used, if provided, instead of default internal templates.

But in case of presets that will be probably provided by another library there should be some mechanism to pass their templates into our component.

I currently can see 2 possible ways (in theory):
1. (simpler) Preset library defines a component that implements our interface that requires a few properties to be defined as `TemplateRef`s. And then user will place both that component and dropdown in the template, grab that component via local template variable and pass as input to dropdown component.
  Downside - it will require 1 extra component to be in the template near every dropdown.
2. Expose a few tokens that can be set as functions that will return `TemplateRef`s from the library template, that library then provides those tokens with it's own functions.
  Then user will place only once component somewhere in the root app component (so that templates will be initialized) and dropdown component will just pick those templates up automatically (via DI).

**Comment by gund** [comment]
I just realized that preset library can define a component (that will implement our interface) and just export it.

Than user, while importing our module, will pass that preset component to the module, so we can store that component in DI, then retrieve it in component, render it, and then get all templates and use them.

**Comment by gund** [comment]
Regarding template presets I did a little exploration in this area to actually check if this is realistic - and it actually does work as anticipated!
Here's the demo repo: https://github.com/gund/test-ng-preset

**Comment by chris--jones** [comment]
Hey, sorry I don't have as much time as I used to.

I agree that templates are probably the way forward, and this would actually allow for reduction of options. For example, there would be no need to have options for css classes / pullRight or multiple checkbox styles if these could be changed via the respective template.

A richer API could allow for responding to or even intercepting events (e.g. to control dynamic title, apply custom selection rules, control how options are counted, or simply tighter integration with an application.) I would also suggest this API allow for dynamic / lazy loading rather than have this driven from options.

Finally the options having hopefully been drastically reduced from the above could be grouped by category to stop them becoming too unruly, e.g.
```
{
  "selection" : {
    "minimum": 1,
    "maximum": 3   
  },
  "search": {
    "enabled": true,
    "minimumLength": 3
  }   
}
```

**Comment by gund** [comment]
Totally agree with @chris--jones above.

About the preset templates, I've worked on the library called [`ng-preset`](https://github.com/gund/ng-preset) that abstracts away instantiation of preset component and adds syntax for libraries to accept 3rd party preset components at the import time.

I guess we can try moving forward with this approach, starting by exposing some basic parts of template to presets.

**Comment by anandSep90** [comment]
It will better to select all and unselect all as toggle functions

**Comment by anandSep90** [comment]
Please ignore previous comment

It will be better to have Select All and Unselect All as a single option with toggle function

**Comment by chris--jones** [comment]
@anandSep90 I think the idea with templates and an updated API is that you could override the default controls and supply your own (e.g. replace the select all and unselect all with a single checkbox).
It makes a lot more sense then us trying to implement and maintain every conceivable combination and permutation of options users might want.

**Comment by anandSep90** [comment]
It will be a cool thing, when a single checkbox option has both the Select All and UnSelect All functionalities. Since it will look elegant and customized for the users to use. It would be appreciated if u could post some example for overriding the default controls.
