### ISSUE TITLE
Dynamically Updating the default text

### ISSUE THREAD

**Issue by HariKiran9** [softsimon/ngx-bootrap-multiselect#351]
Hi,

Is there any way to Dynamically Update the default text in [texts]="mlsTextSettings",

The requirement is when we change the First Select drop down, based on that the second  drop down values has to be refreshed, the values in <ss-multiselect-dropdown> is updated, but the default text is not changing.

Is there any way to update that default text in runtime, i.e., dynamically

Added the Screenshot : 

![image](https://user-images.githubusercontent.com/11388341/34102679-013892a6-e410-11e7-9fb6-af120bf22b1c.png)

**Comment by chris--jones** [comment]
There is no present way to customise this, but it has been suggested as a feature in the next major release.
