### ISSUE TITLE
 (ngModelChange) Calling all ngModelChanges in a form

### ISSUE THREAD

**Issue by mailtovinay** [softsimon/ngx-bootrap-multiselect#356]
Hi,

I have multiple in my form. My first multipleSelect ngModelChange is calling all the ngModelChange of the page. How to restrict it?

**Comment by chris--jones** [comment]
Can you provide a code sample and tell us why this is a problem? The initial binding of the control may cause the event to fire, but you could set an initialized flag or similar and check this if you only want to respond to change events after initialization.
