### ISSUE TITLE
Lazy load issue

### ISSUE THREAD

**Issue by emqubeInd** [softsimon/ngx-bootrap-multiselect#357]
Hello,

It's one of the beautiful component have come across with lazy loading feature,but there is an issue in lazy loading.

lazy load event is getting called more than once.

following are the plunker snippets 

![image](https://user-images.githubusercontent.com/34879975/34373333-6cc0fc60-eb00-11e7-92b6-4f069ec67806.png)

I have set loadViewDistance=0 so as function is getting called when reached at the end.

![image](https://user-images.githubusercontent.com/34879975/34373208-d65415fa-eaff-11e7-8270-d530d11cbe5a.png)

I have console a string to check the occurrence it is getting called.

![image](https://user-images.githubusercontent.com/34879975/34373259-1b6171f6-eb00-11e7-8ef8-49ba8af13168.png)

Following snippet shows it is getting called more than once.

![image](https://user-images.githubusercontent.com/34879975/34373581-f0d7b498-eb01-11e7-809c-d2ef22f712f7.png)

Could you please help on this?
Is it a defect or I am doing something wrong...

Your prompt response is highly appreciated.

**Comment by vehansayvazi** [comment]
I'm having the same issue. 

Also, would it be possible to use something like RXJS debounceTime to avoid too many service calls on searches? Would be nice to have the as a part of the settings we pass in. 

https://www.learnrxjs.io/operators/filtering/debouncetime.html

**Comment by GregKass** [comment]
The ```onLazyLoad``` event is just an enhanced ```scroll``` event. It fires when scrolling reaches the specified range where lazy loading should occur. The check for a change in filter or a change in results length is what determines when an outgoing call should be made to fetch more results. A new call cannot be made on scrolling until the results of the previous call have returned. Those results will then change the scroll range for triggering a new call, so the user has to scroll down before receiving new results. This is how many lazy loading features are implemented.

**Comment by GregKass** [comment]
@vehansayvazi The debounce would really make sense on filter inputs. You could also modify the ```loadData``` function to reflect a debounce time, eg:

```javascript
dbTime = 500
time = new Date().getTime();

if (filter !== this.lastFilter) {
    if (time - this.oldTime < dbTime) {
        clearTimeout(this.timeout);
    }

    this.oldTime = time;
    this.timeout = setTimeout(
        ...
```
and call the rest of the code in the if block with a function within a setTimeout set to the debounce time or else cancel that timeout and generate a new one if a new call is made prior to reaching the timeout.
