### ISSUE TITLE
Drop Down Checkbox not selecting When Data Binded Dynamically 

### ISSUE THREAD

**Issue by anandSep90** [softsimon/ngx-bootrap-multiselect#360]
I need to bind the drop down data dynamically from db and also to select the checkbox
**Html file**
` <ss-multiselect-dropdown 
        [options]="GridOptions" 
         [texts]="myTexts" 
         [settings]="mySettings" 
          [(ngModel)]="GridDataModel">
    </ss-multiselect-dropdown>`

**Ts file**

```
GridOptions: IMultiSelectOption[]
GridDataModel : any[];

 ngOnInit() {
  --db service cal
  --data from database are assigned to DBdata variable
this.GridOptions = DBdata.map(item =>
 ({
         id: item.Id,
         name : item.Name
   }));
this.GridDataModel = [1, 2];
}
```

the checkbox is not selecting based on GridDataModel  value. But when the Static values are given to GridOptions, checkbox is selection is happening

**Comment by abhijagtap73** [comment]
I had same problem may be issue with id, just modify
this.GridOptions = DBdata.map(item =>
 ({
         id: parseInt(item.Id),
         name : item.Name
   }));

**Comment by panchaln0110** [comment]
@anandSep90 @abhijagtap73 Did you find any solutions?
I have same issues
