### ISSUE TITLE
Search icons not displayed correctly on current Bootstrap (v4.0.0-beta.3)

### ISSUE THREAD

**Issue by static-max** [softsimon/ngx-bootrap-multiselect#362]
After going from v4.0.0-beta.2 to v4.0.0-beta.3 the search and clear-search icons next to the search input don't show up correct anymore:

**v4.0.0-beta.2**
![image](https://user-images.githubusercontent.com/13963492/34675423-dd60191e-f489-11e7-8e3b-3b85f45788c1.png)

**v4.0.0-beta.3**
![image](https://user-images.githubusercontent.com/13963492/34675464-02cabe34-f48a-11e7-85b4-34871d729d94.png)

**Comment by ArchSerpo** [comment]
Not working on beta 6 either. Any idea what version is okay?

![image](https://user-images.githubusercontent.com/16471369/38844587-411a6322-4248-11e8-8327-3af00bdeddcb.png)
