### ISSUE TITLE
Refreshing selection Box after modifying options.

### ISSUE THREAD

**Issue by cawena** [softsimon/ngx-bootrap-multiselect#370]
is there a easy way to refresh the multiselect when I remove an options value?

To remove an option....
```
    let index = this.myOptions.findIndex(p => p.id == this.groupId);
    delete this.myOptions[index];
```
..works fine, but the multiselect is not refreshed.

Any Idea?

**Comment by chris--jones** [comment]
try
```
this.myOptions = this.myOptions.filter(option => option.id !== this.groupId)
```

**Comment by cawena** [comment]
that works fine so far, but the button text "select" is gone also....
