### ISSUE TITLE
GroupBy option

### ISSUE THREAD

**Issue by Sneha1993-MS** [softsimon/ngx-bootrap-multiselect#372]
When i specify groupBy option in the settings, it works only if I bind data in ngOnInit, and it does not works if we put else where. I need to keep on change on the data in it but it is not working( it is not changing the data )

**Comment by chris--jones** [comment]
Make sure when you change your model you do it by reference rather than by value.
Assign your model to a new array e.g. via slice(), filter(), concat() rather than mutating values e.g. this.model[index] = newValue

**Comment by Sneha1993-MS** [comment]
@chris--jones I tried it, it is not working for me.
First time it is binding the data. Later if i change the data, the changed data is not binding. It is displaying the previous data itself, if I remove groupBy it the changed data is binding.
