### ISSUE TITLE
Performance issues due to HostListener of global click event

### ISSUE THREAD

**Issue by BlindDespair** [softsimon/ngx-bootrap-multiselect#375]
When you have too many dropdowns on the screen, performance goes horrible all because you have @HostListener('document:click', ...). This initializes as many global listeners as many dropdowns you have and even when you don't need any action but just click around handlers take crazy amount of time, especially as it triggers change detection in entire application. How it can be fixed is:
in toggleDropdown() add 
```
if (!this.isVisible && this.settings.closeOnClickOutside) {
   Observable.fromEvent(document, 'click')
		.takeUntil(this.dropdownClosed)
		.takeUntil(this.destroyed$)
		.subscribe((event: MouseEvent) => this.closeOnGlobalClick(event.target));
}
```

```
closeOnGlobalClick(target) {
	if (!this.element.nativeElement.contains(target)) {
		this.isVisible = false;
		this.dropdownClosed.emit();
	}
}
```

And the whole problem is solved. This will only listen global click event when certain dropdown is opened. And listener will be removed as soon as it's closed, so at a time you will only have 1 listener of global click and only when it's really needed.

**Comment by mwellner** [comment]
Good suggestion! Was that already merged?
