### ISSUE TITLE
Disable a selection from dropdown

### ISSUE THREAD

**Issue by nitin27may** [softsimon/ngx-bootrap-multiselect#378]
I have to display all days of week in the dropdown, but user should not able to select 'Sunday'. How I can achieve this ?

**Comment by diwanshi** [comment]
I see that they have merged a request which has the disabled option but the file has [conflicts](https://github.com/softsimon/angular-2-dropdown-multiselect/pull/350/files/031460ccb3be0963300dccab0e0cd4783f7328fa#diff-54eed86c1c11b4359e10fffde5aa947f) 

I think this will be available in next release.
