### ISSUE TITLE
Changing look while updating project to Angular 5 

### ISSUE THREAD

**Issue by elieahd** [softsimon/ngx-bootrap-multiselect#395]
Once our project was updated to angular 5, the component changed look it seems like no css is applied to the component.

While installing node modules with npm install, a warning has appeared : 
Angular-2-dropdown-select@1.7.0 requires a peer of @angular/common@^4.0.0 but none was installed
angular-2-dropdown-select@1.7.0 requires a peer of @angular/core@^4.0.0 but none was installed
angular-2-dropdown-select@1.7.0 requires a peer of @angular/forms@^4.0.0 but none was installed

**Comment by fstasi** [comment]
same here, I'm trying to fix, but i'm not able to build properly with the given package.json.

Seems like the css file is not included

**Comment by jeesim2** [comment]
same  too, it's UI has broken.
![image](https://user-images.githubusercontent.com/1100831/37695451-abaea798-2d12-11e8-9474-6cb25b19a7c4.png)

any work around?

**Comment by jeesim2** [comment]
Generated html tag of an dropdown-item is different.

### with angular 4
![image](https://user-images.githubusercontent.com/1100831/37696675-c059e500-2d1b-11e8-96e5-81cd33cf9b8e.png)
```
<li _ngcontent-c16="" class="dropdown-item" style="cursor: pointer;">
  <a _ngcontent-c16="" href="javascript:;" role="menuitem" tabindex="-1">
    <input _ngcontent-c16="" type="checkbox"> 
    <span _ngcontent-c16="" style="font-weight: normal;">Unique users</span>
  </a>
</li>
```

### with angular 5
![image](https://user-images.githubusercontent.com/1100831/37696734-0748aaa0-2d1c-11e8-9607-c299bed70d2a.png)
```
<a _ngcontent-c17="" class="dropdown-item active" href="javascript:;" tabindex="-1" ng-reflect-klass="dropdown-item" ng-reflect-ss-autofocus="true">
  <span _ngcontent-c17="" role="menuitem" tabindex="-1">
    <input _ngcontent-c17="" type="checkbox">
    <span _ngcontent-c17="" ng-reflect-ng-class="[object Object]" style="font-weight: normal;">Unique users</span>
  </span>
</a>
```

* when I changed html tag same to angular4 generated in chrome debugger It's UI seems ok.
![image](https://user-images.githubusercontent.com/1100831/37696680-c5d92248-2d1b-11e8-89ff-9342a535aa80.png)
```
<li _ngcontent-c17="" class="dropdown-item active" href="javascript:;" tabindex="-1" ng-reflect-klass="dropdown-item" ng-reflect-ss-autofocus="true">
  <a _ngcontent-c17="" role="menuitem" tabindex="-1">
    <input _ngcontent-c17="" type="checkbox">
    <span _ngcontent-c17="" ng-reflect-ng-class="[object Object]" style="font-weight: normal;">Unique users</span>
  </a>
</li>
```

**Comment by nok32** [comment]
Hy, any solution

**Comment by minhthuan274** [comment]
Me too

**Comment by nitimmerman** [comment]
Same issue here. downgrading to version 1.6.3 for now

**Comment by fstasi** [comment]
guys, I found out... just updagrade to bootstrap 4, and it will work as intended.

Cheers.

**Comment by minhthuan274** [comment]
Sorry, but I'm using template which is used bootstrap 3

**Comment by gsaxam** [comment]
I have the same problem.

**Comment by gsaxam** [comment]
I fixed it using the below `package.json `and running `npm update` after that.

```
"dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/http": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@angular/router": "^5.2.9",
    "@angular/upgrade": "^5.2.9",
    "angular-2-dropdown-multiselect": "1.6.3",
    "angular-in-memory-web-api": "~0.1.1",
    "angular2-jwt": "^0.2.3",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.5.0",
    "semantic-ui-css": "^2.2.12",
    "systemjs": "0.19.39",
    "traceur": "^0.0.96",
    "zone.js": "^0.8.4"
  }
```

**Comment by markbecker7** [comment]
I had the same issue, inserting this css made it look presentable for the time being.

`:host /deep/ ss-multiselect-dropdown .dropdown-item {
  color: black;
  display: inherit;
  padding-left: 15px;
}

:host /deep/ ss-multiselect-dropdown .dropdown-menu > a:hover {
  color: black;
  text-decoration: none;
  background-color: lightgray;
}

:host /deep/ ss-multiselect-dropdown .dropdown-menu > a:focus {
  color: black;
  text-decoration: none;
  outline: none !important;
}`

**Comment by simonaberry** [comment]
@markbecker7 where do you put this css ?
