### ISSUE TITLE
Cannot read property 'disabled' of undefined

### ISSUE THREAD

**Issue by yankeeshadow** [softsimon/ngx-bootrap-multiselect#403]
After upgrading from 1.6.0 to 1.7 for bootstrap 4 final support, the component with  Labels / Parents datas doesn't work and an error thrown in browser console:

MultiselectDropdownComponent.html:1 ERROR TypeError: Cannot read property 'disabled' of undefined
    at MultiselectDropdownComponent.isCheckboxDisabled (dropdown.component.js?1c37:517)
    at Object.eval [as updateRenderer] (MultiselectDropdownComponent.html:1)
    at Object.debugUpdateRenderer [as updateRenderer] (core.es5.js?de3d:13094)
    at checkAndUpdateView (core.es5.js?de3d:12241)
    at callViewAction (core.es5.js?de3d:12601)
    at execEmbeddedViewsAction (core.es5.js?de3d:12559)
    at checkAndUpdateView (core.es5.js?de3d:12237)
    at callViewAction (core.es5.js?de3d:12601)
    at execEmbeddedViewsAction (core.es5.js?de3d:12559)
    at checkAndUpdateView (core.es5.js?de3d:12237)

My usage is instructed by the notes in primary page:

**testbed.component.ts**

`
@Component({
    selector: 'jhi-testbed',
    templateUrl: './testbed.component.html',
})
export class TestbedComponent {
    customizedOptions: IMultiSelectOption[] = [
        { id: 1, name: '汽车品牌', isLabel: true },
        { id: 2, name: '沃尔沃', parentId: 1 },
        { id: 3, name: '宏达', parentId: 1 },
        { id: 4, name: '宝马', parentId: 1 },
        { id: 5, name: 'Colors', isLabel: true },
        { id: 6, name: 'Blue', parentId: 5 },
        { id: 7, name: 'Red', parentId: 5 },
        { id: 8, name: 'White', parentId: 5 }
    ];

   customizedTexts: IMultiSelectTexts = {
        checkAll: 'Select all',
        uncheckAll: 'Unselect all',
        checked: 'item selected',
        checkedPlural: 'items selected',
        searchPlaceholder: '搜索',
        searchEmptyResult: 'Nothing found...',
        searchNoRenderText: 'Type in search box to see results...',
        defaultTitle: 'Select',
        allSelected: 'All selected',
    };
  
    customizedSettings: IMultiSelectSettings = {
        pullRight: true,
        enableSearch: true,
        checkedStyle: 'fontawesome',
        buttonClasses: 'btn btn-info btn-block',
        itemClasses: '',
        containerClasses: 'dropdown-inline',
        selectionLimit: 0,
        dynamicTitleMaxItems: 3,
        displayAllSelectedText: true
    };

}
`

**testbed.component.html**
`
<ss-multiselect-dropdown [options]="customizedOptions" [texts]="customizedTexts" [settings]="customizedSettings"></ss-multiselect-dropdown>`

I have to go back to version 1.6 now.

I checked source code in src/dropdown//dropdown.component.html and found the last few lines of code

`  <ng-template #label>
        <span [class.disabled]="isCheckboxDisabled()">{{ option.name }}</span>
      </ng-template>
`
found no parameters passed to isCheckboxDisabled, is it supposed to be 'option'?

**Comment by ThaiHM** [comment]
I have same issue on 1.7.
I have to back into 1.6.3.

**Comment by pablocabo** [comment]
Same issue on 1.7, back to 1.6.3 to solve

**Comment by gpsimmo** [comment]
this issue still exists on 1.7, is this going to be updated anytime soon?

**Comment by dandouglas** [comment]
It looks like it is fixed in version 1.8.0
