### ISSUE TITLE
Remove/Hide options from multiselect

### ISSUE THREAD

**Issue by Kayeda** [softsimon/ngx-bootrap-multiselect#405]
Is there any way to hide or remove some of the [options] list?

My example: I have this list of countries in a filter pane, and another filter indicates the region (Americas, Europe, etc)... I'd like to limit the options in the country multiselect to only show Americas' countries when the user click on Americas, and hide/remove the other countries. 

I already unselect the ones that are not part of that region, but the user still wants to see only the possible options visible. Is it feasible?

**Comment by Kayeda** [comment]
Ok then.

**Comment by softsimon** [comment]
@Kayeda I believe you should be able to update the list of [options]. So when someone clicking, filter the options and update it with the filtered list, while keeping the full list in another variable.
