### ISSUE TITLE
Override seach method (ignore accented letters)

### ISSUE THREAD

**Issue by bllmhd** [softsimon/ngx-bootrap-multiselect#411]
Is that a way to override the search method?

I use  angular-2-dropdown-multiselect with french letters and i want to change the way the component is searching for results.

In my case, ihave:

// Labels / Parents
myOptions: IMultiSelectOption[] = [
    { id: 1, name: 'recherche', isLabel: true },
    { id: 2, name: 'récapitulatif', parentId: 1 }
];
When i write "re", the result is 'recherche', but i want to see 'recherche' and 'récapitulatif'

**Comment by MamadouOuryBA** [comment]
Hi bllmhd,

I am facing the same problem.
Do you have a solution for this one ?

Thx

**Comment by MamadouOuryBA** [comment]
Hi bllmhd,

I am facing the same problem.
Do you have a solution for this one ?

Thx
