### ISSUE TITLE
closeOnClickOutside doesn't work if I click on another multiselect

### ISSUE THREAD

**Issue by exsoflowe** [softsimon/ngx-bootrap-multiselect#432]
### Expected behaviour
If I click outside current multiselect, it will be closed, even if outside is other multiselect.

### Actual behaviour
I have closeOnClickOutside: true. And I have 2 or more multiselect on page.

I open, for example, 2nd multiselect and then open 1st multiselect.
But 2nd select is opened yet.

### More Info

It doesn't work in v1.7
Bit it works in v1.6.3 (previous version)

demo: https://stackblitz.com/edit/angular-2-dropdown-multiselect-closeonclickoutside-bug

**Comment by felixng1028** [comment]
+1

**Comment by PushkarKashyap** [comment]
Any workaround for this?

**Comment by IntelligaiaVivek** [comment]
Hi i am new to angular family  i am also facing this issue any help is appreciated
