### ISSUE TITLE
Demo Not Working 

### ISSUE THREAD

**Issue by nakulkundra** [softsimon/ngx-bootrap-multiselect#442]
The Demo is not working 

![image](https://user-images.githubusercontent.com/5175294/44502436-195fda80-a6af-11e8-9c21-3173210d841c.png)

sounds like the content delivery network is no more accessible.

**Comment by intellix** [comment]
It should be fixed here but if you need to see an example, I found a couple of demos by searching Stackblitz: https://stackblitz.com/edit/angular2-multiselect-dropdown-bug
