### ISSUE TITLE
ERROR in ../../../node_modules/angular2-multiselect-dropdown/multiselect.component.d.ts.AngularMultiSelect.html(156,46): : Type 'Boolean' is not assignable to type 'boolean'.   'boolean' is a primitive, but 'Boolean' is a wrapper object. Prefer using 'boolean' when possible.

### ISSUE THREAD

**Issue by kannarao** [softsimon/ngx-bootrap-multiselect#448]
I am getting while building prod setup using angular cli and using angular 5. Please help me on this.

**Comment by kannarao** [comment]
I got the issue. Interface angular2-multiselect-dropdown/multiselect.interface.d.ts you are use 'Boolean' instead of 'boolean'.
I have to deploy code

**Comment by Shashikant1991** [comment]
I was having same problem,
but after install previous version from `3.1.0` to `^2.9.0`. 
It solved.

**Comment by vikasverma44** [comment]
I also having same problem but i need 3.1.0 for filterSelectAllText features.

**Comment by vikasverma44** [comment]
> I also having same problem but i need 3.1.0 for filterSelectAllText features.

finally i got the solution :) 

Just update versions of these dependencies in package.json file 
   "@angular/animations": "5.2.0",
    "@angular/common": "5.2.0",
    "@angular/compiler": "5.2.0",
    "@angular/core": "5.2.0",
    "@angular/forms": "5.2.0",
    "@angular/http": "5.2.0",
    "@angular/platform-browser": "5.2.0",
    "@angular/platform-browser-dynamic": "5.2.0",
    "@angular/platform-server": "5.2.0",
    "@angular/router": "5.2.0",

**Comment by daniel-upzzle** [comment]
I am having the same problem. But I need angular4 and with multiselect ^2.9.0 the error persists...

**Comment by facuvegaa** [comment]
any news?
