### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by GregKass** [softsimon/ngx-bootrap-multiselect#452]
I'm wondering if there is any value in me making continuing contributions. The fact that the demo hasn't been working since February and should be relatively easy to fix makes me wonder if this project is still in fact being supported.

**Comment by maxsands1503** [comment]
I wonder if @softsimon can answer this question, or do we have to abandon this package for Angular 7+ support.

**Comment by softsimon** [comment]
Not really supported by me. I only try to merge pull requests and deploy a new version now and then.
