### ISSUE TITLE
Issue is with the data populated inside the dropdown. The data is not populated properly, it's distorted. Attached the screen shots for further details. Please reply asap as the code is already deployed in production.

### ISSUE THREAD

**Issue by Noble-Shiva** [softsimon/ngx-bootrap-multiselect#453]
![emil_figure](https://user-images.githubusercontent.com/25147932/48003755-54619e00-e135-11e8-9704-f9a7246875b9.PNG)
![plugin_info](https://user-images.githubusercontent.com/25147932/48003758-54fa3480-e135-11e8-9966-37d5d0c84f78.PNG)
`
  "devDependencies": {
    "@angular-devkit/core": "^0.8.1",
    "@angular/cli": "^1.5.5",
    "@angular/compiler-cli": "^5.0.5",
    "@angular/language-service": "^5.0.1",
    "@compodoc/compodoc": "^1.0.5",
    "@types/core-js": "^0.9.46",
  }`

Used Angular-CLI version - 1.5.5

Note: Cannot update the angular-cli version as the code is already deployed in production and cannot take any chances.

Thanks in Advance.

**Comment by Noble-Shiva** [comment]
Thanks,

I found the solution by installing the same version using -- `npm install angular-2-dropdown-multiselect@1.6.3`

**Comment by Irfan223** [comment]
hey,
 I need almost same type of filtering but don't know how to do. can you please help to solve this. My problem in i want to filter data which is coming from api and filter using id or itemName through angular2-multiselect-dropdown library.
Thanks in Advance
