### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by Irfan223** [softsimon/ngx-bootrap-multiselect#454]
I am using AngularMultiSelectModule. how can i fetch data from api which is developed in java. Also i want to know how filter data which will come from the api in json format. I am new in angular please help to sort out this problem.

**Comment by maxsands1503** [comment]
That is more of an Angular question and is not exactly germane to the package. However, you may want to checkout [this](https://angular.io/guide/http). And, typescript allows for using the filter array method.
