### ISSUE TITLE
Peer dependency

### ISSUE THREAD

**Issue by dlewis-ald** [softsimon/ngx-bootrap-multiselect#461]
Could the packages peer dependency include a range value (e.g. "^7.0.0"). Currently version 1.9.0 requires peer dependency `@angular/core@7.1.4`, and it looks like the next version will have a peer dependency of `@angular/core@7.2.2.` As these versions do not match what my project has (7.2.14), then I receive the following npm warnings:

```
npm WARN angular-2-dropdown-multiselect@1.9.0 requires a peer of @angular/common@7.1.4 but none is installed. You must install peer dependencies
yourself.
npm WARN angular-2-dropdown-multiselect@1.9.0 requires a peer of @angular/core@7.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN angular-2-dropdown-multiselect@1.9.0 requires a peer of @angular/forms@7.1.4 but none is installed. You must install peer dependencies yourself.
npm
```

These warnings could be avoided if the peer dependencies included a range (e.g. "^7.1.0", or ">= 7.1.0 < 7.3.0")

**Comment by sysmat** [comment]
It is angular 8 now

**Comment by sysmat** [comment]
It is angular 9 now
