### ISSUE TITLE
styling is broken on the latest version

### ISSUE THREAD

**Issue by sebidev999** [softsimon/ngx-bootrap-multiselect#462]
I have updated the version by the latest and noticed styling is broken on the new version.

![image](https://user-images.githubusercontent.com/38624391/65396945-13559500-ddac-11e9-9fc9-3efb0622ce15.png)

It worked well on 1.5.4 but not on 1.9+

This is the previous html structure.
![image](https://user-images.githubusercontent.com/38624391/65397011-8e1eb000-ddac-11e9-8928-becf4e141ab1.png)
And this is the current one.
![image](https://user-images.githubusercontent.com/38624391/65397038-befee500-ddac-11e9-91b6-794f4f398ebb.png)

**Comment by rushvora** [comment]
Seems like v1.6.3 is the last version where Boostrap 3/old CSS/styling works. v1.7 onwards, Bootstrap 4 is needed to style the component.
