### ISSUE TITLE
update to angular 9?

### ISSUE THREAD

**Issue by abrahamsankutty** [softsimon/ngx-bootrap-multiselect#465]
expecting angular 9  updated version

**Comment by cesaric** [comment]
Has anyone tried the current version to see if it works with Angular 9?

**Comment by sysmat** [comment]
It work , but with ng update you should use --force

**Comment by sysmat** [comment]
or alternative angular2-multiselect-dropdown

**Comment by AlecMaliwanag** [comment]
has anyone else had problems not getting it to work with --force?

**Comment by softsimon** [comment]
Updated
