### ISSUE TITLE
css  angular-2-dropdown multiselect not working 

### ISSUE THREAD

**Issue by Sushma-tiwari** [softsimon/ngx-bootrap-multiselect#467]
I have add a angular2 multiselect but here css not applied why ? please check snap:
![image](https://user-images.githubusercontent.com/66738000/91637791-8d64b400-ea28-11ea-813c-9fad1d02859f.png)

**Comment by softsimon** [comment]
What is the problem?
What CSS is not applied?

**Comment by softsimon** [comment]
Better bug description is required.
