### ISSUE TITLE
possible typo in name: bootstrap v bootrap

### ISSUE THREAD

**Issue by stalsma** [softsimon/ngx-bootrap-multiselect#468]
This may be intentional, but it caught me up and sent me in circles for too long.

The module is *Bootstrap* (with extra *st* in middle as expected), but it gets imported from *bootrap* (no st in the middle).
```
import { NgxBoot**st**rapMultiselectModule } from 'ngx-bootrap-multiselect';
```

Similarly, the tag is *bootrap* (w/o the *st*):

```
<ngx-bootrap-multiselect
```

**Comment by softsimon** [comment]
Yes, that's a typo. Didn't see it until you mentioned it just now.
I was going through 3-4 names before settling because NPM complained the package names were all taken or "too similar" to previous libs.

**Comment by stalsma** [comment]
Too bad. I was hoping it was intentional.  Fixing it will be a breaking change for everyone that's integrated it.  But perhaps a global search/replace one time will be a lot better than lots of devs trying to figure out why the compiler is complaining.  It kept telling me that I needed to include it in my module, where it was already included.  What it didn't tell me was that `<ngx-bootstrap-multiselect...` didn't exist anywhere.

**Comment by softsimon** [comment]
But I changed the name just a week ago. Not sure how many people migrated to the new one yet. Better to think long term :)

**Comment by stalsma** [comment]
Are you going to issue a new tag (e.g. 2.1)?  I used npm to uninstall/reinstall the package, but the changes aren't getting picked up.  Even nuked my npm cache and reinstalled.

**Comment by softsimon** [comment]
I confirmed `npm install ngx-bootstrap-multiselect` works which will change:

`"ngx-bootrap-multiselect": "^2.0.0",`
to
`"ngx-bootstrap-multiselect": "^2.1.0",`

updating the import path:
`import { NgxBootstrapMultiselectModule } from 'ngx-bootstrap-multiselect';`
and HTML component tag
`<ngx-bootstrap-multiselect></ngx-bootstrap-multiselect>`

**Comment by stalsma** [comment]
Seems like a good solution.  I just updated my package.json, and got the errors I expected.  One search/replace later and everything is back to where it should be.

**Comment by johnnyharwell03-hue** [comment]
Good
