### ISSUE TITLE
Support for Keyboard shortcuts to improve user experience

### ISSUE THREAD

**Issue by naveedahmed1** [softsimon/ngx-bootrap-multiselect#55]
Please add support for Keyboard shortcuts to improve user experience when filling forms.

For example lets take an example of a form with three inputs where 2nd input is angular-2-dropdown-multiselect.

When user press Tab key while focus is on angular-2-dropdown-multiselect, the focus should be set on the next input i.e. 3rd form field in this case.

Pressing Shift + Tab key from angular-2-dropdown-multiselect should set focus on previous input i.e. angular-2-dropdown-multiselect i.e. 1st form field in this case.

When the angular-2-dropdown-multiselect is open, allow scrolling of options through Up and Down arrow keys. Pressing Spacebar should check the focused option. Pressing Enter Key cloud select the option and close the Dropdown.

When the angular-2-dropdown-multiselect is open, pressing Esc Key should close the Select list, while keeping focus on the Select list (so that when the user press Enter key it should open the select list again).

When the angular-2-dropdown-multiselect is Open, pressing Tab or Shift + Tab key should close the select list and focus should be switched to the next input of the form (or previous input in case of Shift + Tab).

When filters are enabled opening the angular-2-dropdown-multiselect should set focus on the search field. Pressing Tab key on Search field, should set focus on options list (where user can use Up/Down arrow keys to navigate between options), whereas Esc Key should clear the the search text so that user can enter new search term. When the search field is empty pressing Esc key could close the select list.

**Comment by stankuhn** [comment]
This is absolutelly needed for forms used regularly to input data. 
Keyboard navigationa and form filling can be much faster in many cases.
For me using tab properly selects mutiselect in correct order between inputs, so when user hits enter it pops up options. However it is not possible to use arrows to navigate and select options. 
Tab then should close and go to next input in form.

**Comment by asish6292** [comment]
Guys is there any update on this issue..because i have tried to implement the multiselect dropdown with the latest version of "angular-2-dropdown-multiselect": "^1.8.0" as of now using angular5 and bootstrap4 still not able see the keyboard arrow key functionality working or if any one of you have any fix for that please update here...Thanks in advance.

**Comment by thomae82** [comment]
Any Update here?
