### ISSUE TITLE
DropDown Title not updating immediately

### ISSUE THREAD

**Issue by radomeit** [softsimon/ngx-bootrap-multiselect#74]
I had a strange issue where the title of the drop down wasn't updating immediately when the view template was rendered for the first time, it was just showing the default "select" text instead of "3 selected" or the names of the selected items.

It only updated when i clicked anywhere in the parent component.

I was unable to figure out exactly what causes this, but this change fixed it for me:
import { ...     ChangeDetectorRef }
...
    private modelInternal: number[];
    @Input()
    set model(model: number[]) {
        this.modelInternal = model;
        if(this.texts !== undefined && this.texts !== null){
            this.updateNumSelected();
            this.updateTitle();
            this.cd.markForCheck();
        }
    }
    get model() { return this.modelInternal; }
...
    constructor(
 ...         private cd: ChangeDetectorRef) 

Maybe this is useful for you.

**Comment by ipassynk** [comment]
You can try to set selectedOptions to empty array as default in you component
```
selectedOptions: Array<string> = [];
```
and when the componet receives options set them:
```
this.selectedOptions = ['1','2']
```

html template:
```
<ss-multiselect-dropdown
                         [settings]="settings"
                         [options]="options"
                         [(ngModel)]="selectedOptions"
                         (ngModelChange)="onSelectChange($event)"></ss-multiselect-dropdown>
```
